version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: iam-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../iam-database-postgres/init:/docker-entrypoint-initdb.d/
    networks:
      - iam-network
    restart: unless-stopped
  
  iam-adminer:
    image: adminer:latest
    container_name: iam-adminer
    ports:
      - "8091:8091"
    depends_on:
      - postgres
    networks:
      - iam-network

  redis:
    image: redis:7-alpine
    container_name: iam-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - iam-network
    restart: unless-stopped
  
  vault:
    image: hashicorp/vault:1.15
    container_name: iam-vault
    ports:
      - "${VAULT_PORT}:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_ROOT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    networks:
      - iam-network
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: iam-mongodb
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodb_data:/data/db
    networks:
      - iam-network
    restart: unless-stopped

#  notification-service:
#    build:
#      context: ../iam-notification-service
#      dockerfile: Dockerfile
#    container_name: iam-notification-service
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/iam_db
#      SPRING_R2DBC_USERNAME: iam_malak
#      SPRING_R2DBC_PASSWORD: Malak123
#      SPRING_DATA_REDIS_HOST: redis
#      SPRING_DATA_REDIS_PORT: 6379
#      JWT_SECRET: docker-jwt-secret-key
#      EMAIL_PROVIDER: smtp
#      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
#      SMTP_USERNAME: ${SMTP_USERNAME}
#      SMTP_PASSWORD: ${SMTP_PASSWORD}
#      EMAIL_FROM: ${EMAIL_FROM:-noreply@iam-system.com}
#      SMS_PROVIDER: mock
#      AWS_ENABLED: false
#    ports:
#      - "8084:8084"
#    depends_on:
#      - postgres
#      - redis
#    networks:
#      - iam-network
#    volumes:
#      - ./logs:/app/logs


volumes:
  postgres_data:
  redis_data:
  mongodb_data:

networks:
  iam-network:
    driver: bridge
